-- Seed 10 additional recipes (sourced from xiachufang public recipe pages).
-- Schema unchanged; this is pure data insert.

INSERT INTO recipes (id, name, english, category, difficulty, time_minutes, tags, hue1, hue2, image_url, description, hot, sort_order) VALUES
  ('tudou_niurou',  '土豆炖牛肉',          'Potato Beef Stew',           '家常', 2, 40, ARRAY['咸香','下饭','炖煮'],     '#B85A2A', '#5C2A0A', 'https://i2.chuimg.com/a217c52a404a4b69bc04767f59dbaf09_1280w_1707h.jpg', '经典家常 · 软糯入味',     FALSE,  7),
  ('kele_jichi',    '可乐鸡翅',            'Coca-Cola Chicken Wings',     '家常', 1, 35, ARRAY['甜咸','嫩滑','经典'],     '#8B4513', '#3D1F0A', 'https://i2.chuimg.com/09a629c7a3ef4ae0affb2a20e26c4c63_1050w_787h.jpg',  '甜咸经典 · 零失败',       TRUE,   8),
  ('rumo_zhengdan', '肉沫蒸蛋',            'Steamed Egg with Pork',       '家常', 1, 25, ARRAY['嫩滑','下饭','蒸菜'],     '#E8B85C', '#8B5C20', 'https://i2.chuimg.com/7d72e8c257fd42c080a3c54fa1a65ce0_1921w_2560h.jpg', '嫩滑如布丁 · 下饭神器',   FALSE,  9),
  ('liangban_mian', '夏日凉拌面',          'Cold Sesame Noodles',         '凉菜', 1, 20, ARRAY['麻辣','清爽','夏日'],     '#C13D4D', '#5C1820', 'https://i2.chuimg.com/19665048b8ad48d2b25f46d3e2cf344a_1257w_1412h.jpg', '麻辣清爽 · 夏日开胃',     FALSE, 10),
  ('koushui_ji',    '椒麻口水鸡',          'Mouthwatering Chicken',       '川菜', 1, 45, ARRAY['麻辣','开胃','凉菜'],     '#C82E3C', '#5A1218', 'https://i2.chuimg.com/8b14ec0cae0b4ca1aa1b83bc940061f8_1280w_1708h.jpg', '椒麻鲜辣 · 川味凉菜',     TRUE,  11),
  ('shousi_baocai', '手撕包菜',            'Hand-Torn Cabbage',           '家常', 1,  5, ARRAY['酸辣','脆爽','快手'],     '#7AA840', '#3A5028', 'https://i2.chuimg.com/6ea9fa0252a24845a72ad1220b0457aa_3024w_4030h.jpg', '5分钟快手 · 脆爽开胃',    FALSE, 12),
  ('fensi_baocai',  '粉丝鸡蛋炒包菜',      'Cabbage Egg Vermicelli',      '家常', 1, 15, ARRAY['咸香','快手','下饭'],     '#A8B83A', '#5C6820', 'https://i2.chuimg.com/e6ab59abf6b544ed829c2df6c03e64d7_1280w_1592h.jpg', '零失败 · 巨下饭',         FALSE, 13),
  ('shanyao_tang',  '山药排骨汤',          'Pork Rib & Yam Soup',         '汤羹', 1, 50, ARRAY['鲜美','清淡','滋补'],     '#D4C396', '#6B5A38', 'https://i2.chuimg.com/7a3b705b2aeb4b3f9f6377affcfe8890_1280w_1706h.jpg', '鲜香滋补 · 一锅营养',     FALSE, 14),
  ('congyou_ji',    '葱油焖鸡',            'Scallion Braised Chicken',    '家常', 2, 50, ARRAY['葱香','咸鲜','下饭'],     '#6B8E4D', '#38502A', 'https://i2.chuimg.com/51f34ec340a64316bcf2fa51ad4d85bf_530w_699h.png',   '葱油焦香 · 咸鲜下饭',     FALSE, 15),
  ('cuipi_doufu',   '脆皮豆腐',            'Crispy Tofu',                 '家常', 1, 20, ARRAY['酥脆','下饭','素菜'],     '#D69C3D', '#6B4A18', 'https://i2.chuimg.com/e88fc12162e74eb38b1f4303d3205538_1078w_720h.jpg',  '外脆里嫩 · 一口爆汁',     TRUE,  16);

-- ── Ingredients ──────────────────────────────────────────────────────
INSERT INTO recipe_ingredients (recipe_id, name, amount, ord) VALUES
  -- tudou_niurou
  ('tudou_niurou','牛肉','200克',1),
  ('tudou_niurou','土豆','约200克',2),
  ('tudou_niurou','胡萝卜','半根',3),
  ('tudou_niurou','西兰花','适量',4),
  ('tudou_niurou','小葱','适量',5),
  ('tudou_niurou','生抽','2勺',6),
  ('tudou_niurou','老抽','半勺',7),
  ('tudou_niurou','蚝油','1勺',8),
  ('tudou_niurou','淀粉','2勺',9),
  ('tudou_niurou','黑胡椒粉','适量',10),
  ('tudou_niurou','食用油','2勺',11),
  -- kele_jichi
  ('kele_jichi','鸡翅','8个',1),
  ('kele_jichi','可乐','适量',2),
  ('kele_jichi','生抽','1勺',3),
  ('kele_jichi','老抽','1勺',4),
  ('kele_jichi','蚝油','1勺',5),
  ('kele_jichi','料酒','适量',6),
  ('kele_jichi','葱姜蒜','适量',7),
  ('kele_jichi','白芝麻','少许',8),
  -- rumo_zhengdan
  ('rumo_zhengdan','鸡蛋','3个',1),
  ('rumo_zhengdan','肉沫','200克',2),
  ('rumo_zhengdan','葱花','适量',3),
  ('rumo_zhengdan','蚝油','1勺',4),
  ('rumo_zhengdan','生抽','2勺',5),
  ('rumo_zhengdan','盐','1小勺',6),
  ('rumo_zhengdan','温水','蛋液1.5倍',7),
  ('rumo_zhengdan','淀粉水','小半碗',8),
  -- liangban_mian
  ('liangban_mian','面条','1份',1),
  ('liangban_mian','黄瓜','半根',2),
  ('liangban_mian','火腿肠','1根',3),
  ('liangban_mian','香菜','适量',4),
  ('liangban_mian','葱花','适量',5),
  ('liangban_mian','蒜末','适量',6),
  ('liangban_mian','小米辣','3-5个',7),
  ('liangban_mian','白芝麻','适量',8),
  ('liangban_mian','花生米','适量',9),
  ('liangban_mian','生抽','2勺',10),
  ('liangban_mian','醋','2勺',11),
  ('liangban_mian','芝麻酱','1勺',12),
  ('liangban_mian','辣椒粉','1勺',13),
  ('liangban_mian','鸡精','适量',14),
  ('liangban_mian','胡椒粉','适量',15),
  -- koushui_ji
  ('koushui_ji','鸡腿','3只',1),
  ('koushui_ji','小米椒','2个',2),
  ('koushui_ji','青椒','1个',3),
  ('koushui_ji','蒜末','适量',4),
  ('koushui_ji','白芝麻','1勺',5),
  ('koushui_ji','辣椒粉','1勺',6),
  ('koushui_ji','金针菇','1把',7),
  ('koushui_ji','生抽','2勺',8),
  ('koushui_ji','白糖','1小勺',9),
  ('koushui_ji','蚝油','1勺',10),
  ('koushui_ji','花椒油','2勺',11),
  -- shousi_baocai
  ('shousi_baocai','包菜','适量',1),
  ('shousi_baocai','大蒜','4瓣',2),
  ('shousi_baocai','干辣椒','5个',3),
  ('shousi_baocai','生抽','1勺',4),
  ('shousi_baocai','醋','2勺',5),
  ('shousi_baocai','蚝油','1勺',6),
  ('shousi_baocai','白糖','1勺',7),
  ('shousi_baocai','盐','少许',8),
  ('shousi_baocai','鸡精','少许',9),
  -- fensi_baocai
  ('fensi_baocai','包菜','半个',1),
  ('fensi_baocai','粉丝','2把',2),
  ('fensi_baocai','鸡蛋','4个',3),
  ('fensi_baocai','葱花','少许',4),
  ('fensi_baocai','生抽','适量',5),
  ('fensi_baocai','老抽','适量',6),
  ('fensi_baocai','蚝油','适量',7),
  ('fensi_baocai','盐','少许',8),
  ('fensi_baocai','食用油','适量',9),
  -- shanyao_tang
  ('shanyao_tang','排骨','500克',1),
  ('shanyao_tang','山药','1根',2),
  ('shanyao_tang','胡萝卜','1根',3),
  ('shanyao_tang','玉米','1根',4),
  ('shanyao_tang','葱姜','适量',5),
  ('shanyao_tang','料酒','适量',6),
  ('shanyao_tang','盐','少许',7),
  -- congyou_ji
  ('congyou_ji','鸡腿','2只',1),
  ('congyou_ji','大葱','1把',2),
  ('congyou_ji','姜片','3片',3),
  ('congyou_ji','生抽','3勺',4),
  ('congyou_ji','老抽','2勺',5),
  ('congyou_ji','料酒','2勺',6),
  ('congyou_ji','蚝油','1勺',7),
  ('congyou_ji','白糖','1勺',8),
  ('congyou_ji','醋','少许',9),
  ('congyou_ji','胡椒粉','少许',10),
  ('congyou_ji','盐','少许',11),
  -- cuipi_doufu
  ('cuipi_doufu','嫩豆腐','1块',1),
  ('cuipi_doufu','玉米淀粉','约75克',2),
  ('cuipi_doufu','鸡蛋','1个',3),
  ('cuipi_doufu','生抽','2勺',4),
  ('cuipi_doufu','蚝油','1勺',5),
  ('cuipi_doufu','老抽','几滴',6),
  ('cuipi_doufu','白糖','半勺',7),
  ('cuipi_doufu','葱花','适量',8);

-- ── Steps ────────────────────────────────────────────────────────────
INSERT INTO recipe_steps (recipe_id, step_index, title, description, heat, tip) VALUES
  -- tudou_niurou (7 steps)
  ('tudou_niurou',1,'调酱汁','生抽、蚝油、淀粉和少许水搅匀备用','','酱汁要提前调好'),
  ('tudou_niurou',2,'腌制牛肉','牛肉切丁加生抽、老抽、淀粉抓匀后加油腌10分钟','','切小块更入味'),
  ('tudou_niurou',3,'处理蔬菜','胡萝卜和土豆切丁,西兰花提前焯水备用','',''),
  ('tudou_niurou',4,'煎土豆胡萝卜','热锅冷油,下胡萝卜丁和土豆丁煎炒至微焦盛出','大火','热锅冷油不粘锅'),
  ('tudou_niurou',5,'炒牛肉','热锅冷油爆香葱花,倒入牛肉炒至变色','大火','大火爆炒使牛肉更鲜嫩'),
  ('tudou_niurou',6,'汇合烹饪','倒入土豆胡萝卜丁和酱汁,炒至汤汁浓稠','中火',''),
  ('tudou_niurou',7,'出锅','倒入焯水后的西兰花翻炒均匀即可','中火',''),
  -- kele_jichi (5 steps, condensed)
  ('kele_jichi',1,'改刀焯水','鸡翅改刀,冷水下锅加料酒焯3分钟,冲洗干净','大火','改刀更入味'),
  ('kele_jichi',2,'煎至金黄','锅中少油,鸡翅煎至两面微黄','中火','增加香气'),
  ('kele_jichi',3,'调味上色','下葱姜蒜爆香,加生抽、蚝油、老抽炒匀','中火',''),
  ('kele_jichi',4,'焖煮可乐','倒入可乐没过鸡翅,中火焖15-20分钟','中火','时间长更入味'),
  ('kele_jichi',5,'收汁出锅','大火收浓汤汁,撒白芝麻装盘','大火','配米饭最香'),
  -- rumo_zhengdan (5 steps)
  ('rumo_zhengdan',1,'调蛋液','鸡蛋打散加盐和1.5倍温水,过筛撇浮沫','','过筛蛋液更细腻'),
  ('rumo_zhengdan',2,'蒸蛋','盖保鲜膜扎孔,中火上锅蒸12分钟','中火','防止冷凝水滴入'),
  ('rumo_zhengdan',3,'炒肉沫','少油下肉沫炒散,加生抽2勺、蚝油1勺、盐','大火','肉沫要炒散'),
  ('rumo_zhengdan',4,'勾芡','加淀粉水煮沸,关火撒葱花','大火','增加浓度和挂汁感'),
  ('rumo_zhengdan',5,'组合','蒸蛋上淋肉沫酱汁,再撒葱花即可','','趁热吃风味最佳'),
  -- liangban_mian (5 steps, condensed)
  ('liangban_mian',1,'煮面','面条下锅煮熟,捞出过凉水','大火','过凉水更有嚼劲'),
  ('liangban_mian',2,'激香','葱花、蒜末、辣椒粉、白芝麻装碗,泼热油激香','中火',''),
  ('liangban_mian',3,'调料汁','加鸡精、生抽2勺、醋2勺、芝麻酱1勺、小米辣,加凉白开搅匀','',''),
  ('liangban_mian',4,'装碗配菜','面装碗,放黄瓜丝、火腿肠丁','',''),
  ('liangban_mian',5,'拌匀','倒入料汁拌匀,撒花生米和香菜即可','','夏日绝配'),
  -- koushui_ji (3 steps, condensed)
  ('koushui_ji',1,'调料汁','青椒小米椒切圈,与蒜末、辣椒粉、白芝麻、葱花同碗,泼热油激香,加生抽、白糖、蚝油、花椒油、鸡汤搅匀','','椒麻味的灵魂'),
  ('koushui_ji',2,'煮鸡腿','鸡腿冷水加葱姜料酒,大火煮开撇沫,中火煮15分钟,捞出冰水浸10分钟','大火转中火','冰水浸泡保持Q弹'),
  ('koushui_ji',3,'组盘','金针菇煮熟铺底,鸡腿切块叠上,淋料汁静置20分钟入味','','静置越久越入味'),
  -- shousi_baocai (5 steps)
  ('shousi_baocai',1,'手撕包菜','包菜手撕成块,洗净控干','','手撕更易入味,不用刀'),
  ('shousi_baocai',2,'调料汁','生抽1勺+醋2勺+蚝油1勺+白糖1勺+盐+鸡精拌匀','','料汁先调好节省时间'),
  ('shousi_baocai',3,'爆香','小火下蒜末和干辣椒翻炒出香','小火','防止辣椒糊'),
  ('shousi_baocai',4,'快炒包菜','下包菜中大火翻炒至断生','中火','保留脆爽口感'),
  ('shousi_baocai',5,'调味出锅','倒入料汁大火翻炒均匀即可','大火','快炒锁味'),
  -- fensi_baocai (5 steps)
  ('fensi_baocai',1,'泡粉丝','粉丝温水泡软,沥干加少许油和老抽拌匀','','防止下锅粘成团'),
  ('fensi_baocai',2,'炒鸡蛋','热锅凉油,打鸡蛋炒至金黄,加葱花爆香','大火',''),
  ('fensi_baocai',3,'炒包菜','放切好的包菜,大火快炒至变软断生','大火','全程大火保持脆爽'),
  ('fensi_baocai',4,'下粉丝','倒入粉丝,加生抽、蚝油、盐快速翻炒均匀','大火',''),
  ('fensi_baocai',5,'出锅','加少许蒜末再翻匀即可','大火','爱辣可加一点小米辣'),
  -- shanyao_tang (4 steps)
  ('shanyao_tang',1,'处理食材','胡萝卜切滚刀块、玉米剁段、山药去皮切段','',''),
  ('shanyao_tang',2,'排骨焯水','排骨冷水加葱姜料酒,水开煮3分钟捞出','大火','去血沫腥味'),
  ('shanyao_tang',3,'炒香注水','少油爆香葱姜,翻炒排骨片刻,一次性加足水','中火','一次加水避免中途补水'),
  ('shanyao_tang',4,'炖煮','放胡萝卜、玉米、山药,转中小火炖40分钟,加盐再炖2分钟','中小火','山药晚放免化散'),
  -- congyou_ji (3 steps)
  ('congyou_ji',1,'腌鸡块','鸡腿剁块沥干,加料酒、醋、胡椒粉、白糖、生抽、老抽、蚝油、盐拌匀,腌30分钟','','口味偏咸可减生抽'),
  ('congyou_ji',2,'煎葱焖鸡','锅热油,葱段姜片煎至焦黄捞出,下鸡块翻炒至变色,倒入腌汁,盖盖中小火焖15分钟','中小火','保留葱油增香'),
  ('congyou_ji',3,'出锅','焖至鸡熟透,撒葱花装盘','','葱花点缀更香'),
  -- cuipi_doufu (3 steps)
  ('cuipi_doufu',1,'调酱汁','生抽、老抽、蚝油、白糖加1勺玉米淀粉和半碗水搅匀备用','','淀粉要彻底化开'),
  ('cuipi_doufu',2,'裹粉煎制','豆腐切厚片,先裹玉米淀粉再裹蛋液,下锅煎至两面金黄','中火','轻拿轻放避免散裂'),
  ('cuipi_doufu',3,'焖煮上色','倒入酱汁,小火焖至汤汁浓稠,撒葱花出锅','小火','轻翻保持豆腐完整');
